version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html

  amplify-agent:
    image: nginx-amplify-agent:latest
    container_name: amplify-agent
    environment:
      - API_KEY=69e5fbc8181c05bb14642394174bb0b1
      - AMPLIFY_IMAGENAME=nginx:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
      - /proc:/usr/share/proc:ro
      - /sys/fs/cgroup:/usr/share/sys/fs/cgroup:ro

  nginx-manager:
    image: nginx-manager:latest
    container_name: nginx-manager
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=nginx
      - NGINX_PORT=80
    depends_on:
      - nginx
